### PR TITLE
Support serialization to and from std::vector

### PR DESCRIPTION
**Pull request by pfeatherstone**
This PR adds support for serializing to and from ```std::vector<char>```, ```std::vector<int8_t>``` and ```std::vector<uint8_t>```. It's very rare that people use ```std::shared_ptr<char>``` as a buffer container, instead of something standard like ```std::vector<char>```. So supporting serialization to and from these containers means people can freely serialize to their buffers without having to do extra manual memory allocations and copies.

### CODE REVIEW

**Comment by pfeatherstone** [comment]
@niXman what do you think?

**Comment by pfeatherstone** [comment]
Trying to familiarize myself with the unit testing stuff. Not sure what's the best thing to do to test this stuff.

**Comment by pfeatherstone** [comment]
I've added ```saved_size()``` as a bonus feature. It means you can pre-allocate the exact memory required for the serialization. This is useful if you want to serialize to ```std::vector``` and want to reserve the memory, i.e. set the capacity, to avoid unecessary buffer growth.

**Comment by pfeatherstone** [comment]
Just added unit tests for ```saved_size()```. The unit test demonstrates why it's useful. The buffer size is exactly the size it should be and you only resize once!

**Comment by pfeatherstone** [comment]
Not sure if this is a better idea. Rather than having one extra flag ```yas::mem2``` and template the byte parameter of ```yas::vector_ostream```, i'm tempted to have flags : ```yas::memvc``` (for "**mem**ory **v**ector **c**har"), ```yas::memvsi``` (for "**mem**ory **v**ector **s**igned **i**nt8") and ```yas::memvui``` (for "**mem**ory **v**ector **u**nsigned **i**nt8"). Then depending on the flag, determine what the byte type is.

**Comment by pfeatherstone** [comment]
Otherwise, if you want to save to ```vector<char>``` you either do:
```
std::vector<char> buf;
 yas::save<yas::binary|yas::mem2>(yas::vector_ostream<char>(buf), obj);
```

or 

```
std::vector<char> buf = yas::save<yas::binary|yas::mem2,char>(obj);
```

The first version is fine, but in the second one, I don't really like the ```char``` template parameter. It's a bit out of place.

Maybe something like this would be "prettier" :
```
std::vector<char> buf = yas::save<yas::binary|yas::memvc>(obj);
```

We would need better names than ```yas::memvc```, ```yas::memvsi``` and ```yas::memvui```. They are a bit shit. But I think the idea is good. 

Lastly, I'm tempted to NOT template ```yas::vector_ostream``` and have different constructors for ```vector<char>```, ```vector<int8_t>``` and ```vector<uint8_t>``` and let ```yas::vector_ostream``` decide which buf to serialize to. From a user perspective, ```yas::vector_ostream``` is only really a type decorator for passing a vector to ```yas::save``` and the byte template parameter is distracting and could be removed. For example, ```dlib::vectorstream``` from the dlib library is not templated and handles all 3 types of vectors fine and looks better for it.

**Comment by pfeatherstone** [comment]
Tried the idea of splitting ```yas::mem2``` into 3. You have to add quite a bit of code so not sure if it's worth it. Also, doing that means users can have flag:
```
constexpr std::size flags = yas::memvc | yas::memvsi | yas::memvui
```
which is not good and it's not clear to the user which will be chosen. So probably not a good idea, and best to stick with a combination of ```yas::mem2``` and a byte template parameter.

**Comment by niXman** [comment]
great job @pfeatherstone !

give me some time so I can re-think the idea and the implementation.

**Comment by pfeatherstone** [comment]
@niXman Thank you. I look forward to this.

**Comment by pfeatherstone** [comment]
I've removed ```yas::mem2``` and just use overloading to support ```std::vector```. This is a bit simpler I think.

**Comment by pfeatherstone** [comment]
@niXman Have you had a chance to look at this?

**Comment by niXman** [comment]
@pfeatherstone  I'm sorry, but I don't have time... I need a few more days.

**Comment by niXman** [comment]
great job, merged!

thank you!

**Pull request merged**
