### PR TITLE
The binary_istream checks the stored size on read

### PR DESCRIPTION
**Pull request by marcbull**
If in the compacted mode, the serialized size is greater than the size of the datatype to store the value into, a exception is thrown.

Hi!

As in my previous commit I used the speed test to ensure the changes don't degrade the performance.

### CODE REVIEW

**Comment by niXman** [comment]
Good point, thank you!

But `compacted_storage_size` test not passed in `json` mode ;)

> json  : compacted_storage_size   -> [std::exception]: /home/travis/build/niXman/yas/tests/base/../../include/yas/types/utility/object.hpp(175): no expected chars ','

**Comment by niXman** [comment]
> As in my previous commit I used the speed test to ensure the changes don't degrade the performance.

Be better to use this tests for compar: https://github.com/fraillt/cpp_serializers_benchmark

**Comment by marcbull** [comment]
Thank you, for the nice words! :-)

After the CI build failed I tried to understand the problem, but I couldn't figure it out. It seems I have to dig deeper into the json part. ;-)

Okay, I will use if for future benchmarks.

**Comment by niXman** [comment]
> After the CI build failed I tried to understand the problem, but I couldn't figure it out. It seems I have to dig deeper into the json part. ;-)

Just disable this test for json/text modes ;)

**Comment by niXman** [comment]
`yas::is_binary_archive<typename archive_traits::oarchive_type>::value`

**Comment by niXman** [comment]
> Just disable this test for json/text modes ;)

Hmm... Something is wrong here... This test seems to be correct for these modes...

**Comment by niXman** [comment]
Ok, I'll merge and try to figure it out on the my local machine.

**Comment by niXman** [comment]
I understood!

This is because `compacted_storage_size` test, in `json` mode for reading int16 the buffer of size `sizeof (T) * 2` is implied. And from `istream` readed `sizeof (T) * 2` bytes, but the `istream` the "tail" remains because `4294967295` was written to the stream, which equals ten bytes.

**Comment by niXman** [comment]
So, I think the `compacted_storage_size` test should be allowed only for binary mode.

I'll fix it.

**Comment by niXman** [comment]
Or, perhaps, have any thoughts about this?

**Comment by marcbull** [comment]
> So, I think the `compacted_storage_size` test should be allowed only for binary mode.

From my point of view, the throw exception could be okay. The stream contains a 4 byte value and a 2 byte value. The istream only reads 2 bytes of the actual 4 bytes, so the exception that a ',' is missing is valid.

**Comment by niXman** [comment]
fixed in `master`. closed.

**Pull request merged**
