### PR TITLE
Update CI workflow with GitHub actions

### PR DESCRIPTION
**Pull request by tusharpm**
- fix test errors
- add logic to save non-conforming vector bool on macOS

### CODE REVIEW

**Comment by niXman** [comment]
hi,

have you seen this?: https://ci.appveyor.com/project/niXman/yas/builds/43784532

**Comment by tusharpm** [comment]
Yes, I saw the failure. However, the [Appveyor build is failing since November 1, 2021](https://ci.appveyor.com/project/niXman/yas/history). Also, [the Travis build since June 1, 2021](https://travis-ci.org/github/niXman/yas/builds).

This change replaces the Appveyor and Travis CI with GitHub actions: [sample build](https://github.com/tusharpm/yas/actions/runs/2455347492).

**Comment by niXman** [comment]
merged, thanks!

**Comment by tusharpm** [comment]
Thanks for merging this change. The Appveyor integration needs to be disabled manually. I don't recall if it is done from GitHub repo settings or Appveyor site now.

**Pull request merged**
