### PR TITLE
YAS link error fix

### PR DESCRIPTION
**Pull request by askamn**
Added a macro check to prevent unnecessary inclusion of abseil types.

### CODE REVIEW

**Comment by niXman** [comment]
@askamn have you tried to build the `yas-base-test` project after this fix?

I am still getting errors:
```
CMake Error at CMakeLists.txt:31 (add_subdirectory):
  add_subdirectory given source "/usr/local/abseil-cpp" which is not an
  existing directory.
```

**Comment by askamn** [comment]
But tests are supposed to test Abseil also correct? You only asked to add Abseil to tests also. 
I implemented the absl tests the same way boost is implemented. yas-base-test depends upon Boost as well as Abseil. 

However, I tried simply linking the absl to a simple CMake project without absl and boost and everything compiled just fine.

**Comment by niXman** [comment]
I wanted to point out that if the user does not have `boost` installed and the user does not define the `YAS_SERIALIZE_BOOST_TYPES` macro, the test will still be successfully built.

**Comment by niXman** [comment]
@askamn

do you plan to continue working on this PR?

**Comment by niXman** [comment]
another question is, why do you need to link `yas-base-test` project with Abseil libraries, if those containers that you added support are template?
isn't it enough just to specify the path to the header files?

**Comment by askamn** [comment]
No, apparently the headers do not expose the full functionality of absl that's why it has to be linked. Maybe we can put an option to build and link with abseil in Cmake?

**Comment by niXman** [comment]
@askamn 

please re-do this so that the build and installation of Abseil is done in a pre-step.

ideally, in CMakeLists you need to check if `YAS_SERIALIZE_ABSL_TYPES` is defined, and if so - add the Abseil libraries necessary for linking.

**Comment by askamn** [comment]
Hi @niXman , I have fixed the issue for abseil. 
And to your point that if you don't have boost installed the tests will still build, they don't, there is some compilation error. Also, you need to explicitly undefine/remove the definitions from CMakeLists to make it work. But that might have as well worked with Abseil where you could just remove the link step for absl. Anyways, I just added a check for a Cmake configure argument YAS_SERIALIZE_ABSL_TYPES and it seems to be working fine.

Also, another issue I found is if I remove boost define using remove_definitions(), the tests don't compile. Apparently there is some issue in your implementation of __YAS_PP_TUPLE_IS_EMPTY which throws a bunch of syntax errors. I tried fixing it but I am not that good :P 
I will see if I can fix it.

**Comment by niXman** [comment]
Hi,

> Also, you need to explicitly undefine/remove the definitions from CMakeLists to make it work.

yes, that's what I meant when I wrote:
> if the user does not have boost installed and the user does not define the YAS_SERIALIZE_BOOST_TYPES macro, the test will still be successfully built.

sorry :(

next:
> Anyways, I just added a check for a Cmake configure argument YAS_SERIALIZE_ABSL_TYPES and it seems to be working fine.

the difference is that when using `boost` types in the test, there is no linking stage.
thus, I assumed you would do the same: if user explicitly commented out `YAS_SERIALIZE_ABSL_TYPES` - the linking stage with Abseil libraries will be ignored.

in addition, I assumed that you would check the preprocessor options for the presence of `YAS_SERIALIZE_ABSL_TYPES` and if so - then link with the Abseil libraries.
I'm new to CMake and don't know if this is possible?

I'm sorry if I'm not making myself clear :(

**Comment by niXman** [comment]
> Also, another issue I found is if I remove boost define using remove_definitions(), the tests don't compile.

hmm...

but if you commented out `YAS_SERIALIZE_BOOST_TYPES` then all is OK?
that is, the problem is with ` remove_definitions()` ?

**Comment by niXman** [comment]
boost case: https://github.com/niXman/yas/blob/master/include/yas/object.hpp#L154
no boost case: https://github.com/niXman/yas/blob/master/include/yas/object.hpp#L183

**Comment by askamn** [comment]
No no, It will happen either way, whether  you comment or use remove_definitions. There is some issue with the Macro i guess (Or maybe some missing C++ include? Not sure). It complains about missing arguments, missing parentheses, etc. However, if I comment out all the tests in the tests() function except for the last one which takes an extra parameter: https://github.com/niXman/yas/blob/master/tests/base/main.cpp#L404 it works just fine. So it has something to do with the last argument.

**Comment by askamn** [comment]
> in addition, I assumed that you would check the preprocessor options for the presence of `YAS_SERIALIZE_ABSL_TYPES` and if so - then link with the Abseil libraries.
> I'm new to CMake and don't know if this is possible?

I am new to Cmake too :P but checking for just the macro and relying on commenting it out would not be a good thing to do. Infact with the current one, I can just pass in a variable while running cmake configure `cmake .. -DYAS_SERIALIZE_ABSL_TYPES=TRUE` and it would enable Abseil support and define all the macros, link the lib, etc. 

To be completely honest, none of this actually matters outside the test bench, because yas doesn't use CMake as it is a header-only library 😄
To anyone wanting to use it, (like me) I just have to include the headers. That's it. I link Absl separately anyways as part of the main project. 
And for anyone not wanting to use Absl, they just don't have to include the headers like `abseil_types.hpp`

**Comment by niXman** [comment]
> It will happen either way, whether you comment or use remove_definitions.

I rechecked again and I have no such error.
I also double-checked that I do not have another copy of boost in my system.
strange...

**Comment by niXman** [comment]
@askamn 

please look at this: https://github.com/niXman/yas/blob/master/tests/base/CMakeLists.txt#L43
`add_subdirectory()` is not in if-scope ;)

**Comment by niXman** [comment]
and this too: https://github.com/niXman/yas/blob/master/tests/base/CMakeLists.txt#L54

**Comment by niXman** [comment]
but this block is redundant: https://github.com/niXman/yas/blob/master/tests/base/CMakeLists.txt#L154

**Comment by askamn** [comment]
Oh damn... How did I miss those O.o. I will fix them.

**Comment by askamn** [comment]
> but this block is redundant: https://github.com/niXman/yas/blob/master/tests/base/CMakeLists.txt#L154

How ? Do you mean because there's another check just below `add_executable`?

**Comment by niXman** [comment]
because the presence of header files that are not even used is not a problem, because the body of these files is blocked by the PP guards: https://github.com/niXman/yas/blob/master/include/yas/types/abseil/btree_map.hpp#L38

**Comment by niXman** [comment]
> How ? Do you mean because there's another check just below add_executable?

just add these files to the same place as all test files. additional check is not needed.

**Pull request merged**
