### PR TITLE
CMake file changes for Absl support

### PR DESCRIPTION
**Pull request by askamn**

### CODE REVIEW

**Comment by niXman** [comment]
thank you!

**Comment by askamn** [comment]
:) If anyone requires, I can add support for more absl types.

**Comment by niXman** [comment]
why not ;)

**Comment by niXman** [comment]
@askamn 

hi, again :)

any idea why this happens?: https://travis-ci.org/github/niXman/yas/jobs/737987613#L2805

**Comment by askamn** [comment]
I have no idea, I have never seen errors such as this. Is it possible
because of some old cache being present?

**Comment by niXman** [comment]
> Is it possible because of some old cache being present?

I don't know...

**Pull request merged**
